sudo: required
language: cpp

compiler:
  - clang
  - gcc


# whitelist
branches:
  only:
    - master


script:"mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make && ./CMakeHelloWorld"